lint:
  actions_nf_test: false
  container_configs: false
  modules_config: false
  multiqc_config: false
  nf_test_content: false
  actions_awsfulltest: false
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: "Samuel Ruiz-Pérez, Qian Du, Alva Biran, Anja Groth, Nicolas Alcaraz"
  description: a reproducible nascent chromatin sequencing analysis pipeline for epigenome replication studies.
  force: false
  is_nfcore: false
  name: crepas
  org: grothlab
  outdir: .
  version: 1.0.1