lint:
  actions_awsfulltest: false
  actions_nf_test: false
  container_configs: false
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-crepas_logo_light.png
    - conf/modules.config
    - docs/images/nf-core-crepas_logo_light.png
    - docs/images/nf-core-crepas_logo_dark.png
  modules_config: false
  multiqc_config: false
  nf_test_content: false
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: "Samuel Ruiz-P\xE9rez, Qian Du, Alva Biran, Anja Groth, Nicolas Alcaraz"
  description: a reproducible nascent chromatin sequencing analysis pipeline for epigenome
    replication studies.
  force: false
  is_nfcore: false
  name: crepas
  org: grothlab
  outdir: .
  version: 1.0.1
