# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "sambamba_index"
description: Index a coordinate-sorted BAM file
keywords:
  - index
  - bam
  - bai
  - sambamba
tools:
  - "sambamba":
      description: "Tools for working with SAM/BAM data"
      homepage: "https://lomereiter.github.io/sambamba/docs/sambamba-view.html"
      documentation: "https://lomereiter.github.io/sambamba/docs/sambamba-view.html"
      tool_dev_url: "https://github.com/biod/sambamba"
      doi: "10.1093/bioinformatics/btv098"
      licence: ["GPL v2"]
      identifier: "biotools:sambamba"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: Coordinate-sorted BAM file to index
        pattern: "*.bam"
        ontologies:
          - edam: "http://edamontology.org/format_2572" # BAM
output:
  bai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bai":
          type: file
          description: BAM index file
          pattern: "*.bai"
          ontologies:
            - edam: "http://edamontology.org/format_3327" # BAI
  versions_sambamba:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "sambamba":
          type: string
          description: The name of the tool
      - "sambamba --version 2>&1 | grep -m1 sambamba | awk '{print $2}'":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "sambamba":
          type: string
          description: The name of the tool
      - "sambamba --version 2>&1 | grep -m1 sambamba | awk '{print $2}'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@samuelruizperez"
maintainers:
  - "@samuelruizperez"
