# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "bam_downsample"
description: |
  Downsample a BAM file with Picard DownsampleSam to a target number of reads (endogenous and/or
  spike-in), then index and run samtools stats, flagstat and idxstats
keywords:
  - downsample
  - bam
  - spikein
  - picard
components:
  - picard/downsamplesam
  - bam_flagstat_mapped
  - bam_stats_samtools
input:
  - ch_bam_index:
      description: |
        Input BAM file and its index
        Structure: [ val(meta), path(bam), path(index) ]
  - ch_fasta_fai:
      type: file
      description: |
        Reference fasta file and its index
        Structure: [ val(meta), path(fasta), path(fai) ]
  - genome:
      type: string
      description: Endogenous genome identifier, e.g. 'hg38'
  - spikein_genome:
      type: string
      description: Spike-in genome identifier, e.g. 'mm10'
  - downsampling_method:
      type: string
      description: Downsampling method to use, e.g. 'min_by_type'
  - downsampling_endo_threshold:
      type: integer
      description: Target number of endogenous reads to downsample to
  - downsampling_exo_threshold:
      type: integer
      description: Target number of spike-in reads to downsample to
output:
  - bam:
      description: |
        Downsampled BAM file
        Structure: [ val(meta), path(bam) ]
  - index:
      description: |
        Index of the downsampled BAM file
        Structure: [ val(meta), path(index) ]
  - stats:
      description: |
        File containing samtools stats output
        Structure: [ val(meta), path(stats) ]
  - flagstat:
      description: |
        File containing samtools flagstat output
        Structure: [ val(meta), path(flagstat) ]
  - idxstats:
      description: |
        File containing samtools idxstats output
        Structure: [ val(meta), path(idxstats) ]
authors:
  - "@samuelruizperez"
maintainers:
  - "@samuelruizperez"
