# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: fastq_align_bowtie
description: Align reads to a reference genome using bowtie (v1) then sort with samtools
keywords:
  - align
  - fasta
  - genome
  - reference
  - bowtie
components:
  - bowtie/align
  - samtools/sort
  - samtools/index
  - samtools/stats
  - samtools/idxstats
  - samtools/flagstat
  - bam_sort_stats_samtools
input:
  - ch_reads:
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
        Structure: [ val(meta), [ path(reads) ] ]
  - ch_index:
      description: |
        Bowtie (v1) genome index files
        Structure: [ val(meta2), path(index) ]
  - save_unaligned:
      type: boolean
      description: |
        Save reads that do not map to the reference (true) or discard them (false)
      pattern: "true|false"
  - ch_fasta_fai:
      type: file
      description: |
        Reference fasta file and its index
        Structure: [ val(meta3), path(fasta), path(fai) ]
output:
  - bam_orig:
      description: |
        BAM file produced by bowtie
        Structure: [ val(meta), path(bam) ]
  - log_out:
      description: |
        Bowtie alignment log
        Structure: [ val(meta), path(log) ]
  - fastq:
      description: |
        Unaligned FastQ files, when save_unaligned is true
        Structure: [ val(meta), path(fastq) ]
  - bam:
      description: |
        BAM file ordered by samtools
        Structure: [ val(meta), path(bam) ]
  - index:
      description: |
        Index of the ordered BAM file
        Structure: [ val(meta), path(index) ]
  - stats:
      description: |
        File containing samtools stats output
        Structure: [ val(meta), path(stats) ]
  - flagstat:
      description: |
        File containing samtools flagstat output
        Structure: [ val(meta), path(flagstat) ]
  - idxstats:
      description: |
        File containing samtools idxstats output
        Structure: [ val(meta), path(idxstats) ]
authors:
  - "@drpatelh"
  - "@samuelruizperez"
maintainers:
  - "@samuelruizperez"
