---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-genomicalignments=1.38.0
  - bioconda::bioconductor-genomicfeatures=1.54.1
  - conda-forge::r-argparse=2.2.3
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-ggplot2=3.5.1
  - conda-forge::r-ggpmisc=0.5.6
  - conda-forge::r-ggpubr=0.6.0
  - conda-forge::r-ggrepel=0.9.5
  - conda-forge::r-hexbin=1.28.3
  - conda-forge::r-latex2exp=0.9.6
  - conda-forge::r-rcolorbrewer=1.1_3
  - conda-forge::r-reshape2=1.4.4
